version: 0.1.0-{build}
configuration:
  - Release
platform: Any CPU
image: Visual Studio 2017
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - dev
  - master
build_script:  
- ps: .\Build.ps1
test: off  
artifacts:  
- path: artifacts/*.nupkg

#---------------------------------#
#  Skip builds for doc changes    #
#---------------------------------#
skip_commits:
  # Regex for matching commit message
  message: /docs.*/